name: pdgnn
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.6.2
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cuda-version=12.5
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.10.0.4
  - libcurand=10.3.6.39
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.3.0
  - pip=24.0
  - psutil=5.9.0
  - pybind11-abi=4
  - pyg=2.2.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - pytorch=1.13.1
  - pytorch-cluster=1.6.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.1
  - pytorch-sparse=0.6.17
  - readline=8.2
  - requests=2.32.2
  - scikit-learn=1.4.2
  - scipy=1.13.0
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - torchaudio=0.13.1
  - torchvision=0.14.1
  - tqdm=4.66.4
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - alembic==1.13.2
      - antlr4-python3-runtime==4.9.3
      - async-timeout==4.0.3
      - attrs==23.2.0
      - click==8.1.7
      - colorlog==6.8.2
      - contourpy==1.2.1
      - cycler==0.12.1
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - fastdtw==0.3.4
      - fonttools==4.53.0
      - frozenlist==1.4.1
      - fsspec==2024.5.0
      - futures==3.0.5
      - gensim==4.3.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - gurobipy==11.0.3
      - hydra-core==1.3.2
      - kiwisolver==1.4.5
      - lightning==2.2.2
      - lightning-utilities==0.11.2
      - mako==1.3.5
      - matplotlib==3.9.0
      - multidict==6.0.5
      - networkx==3.3
      - omegaconf==2.3.0
      - optuna==4.0.0
      - optuna-integration==4.0.0
      - packaging==24.0
      - platformdirs==4.2.2
      - protobuf==4.25.3
      - pyg-lib==0.4.0+pt113cu117
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.2.5
      - pyyaml==6.0.1
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==7.0.4
      - smmap==5.0.1
      - sqlalchemy==2.0.34
      - torchmetrics==1.4.0.post0
      - wandb==0.17.0
      - wrapt==1.16.0
      - yarl==1.9.4

