# _target_: pytorch_lightning.Trainer

# default values for all trainer parameters
enable_checkpointing: True
default_root_dir: null
gradient_clip_val: 0.5
overfit_batches: 0.0
check_val_every_n_epoch: 1
fast_dev_run: False
accumulate_grad_batches: 1
max_epochs: 100
min_epochs: 1
max_steps: -1
min_steps: null
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
val_check_interval: 1.0
log_every_n_steps: 1
accelerator: auto

